### ISSUE TITLE
Send WoL without connection to AP

### ISSUE THREAD

**Issue by sepp89117** [a7md0/WakeOnLan#1]
Hi, is it possible to send a WoL without having a connection to an access point?
I'm working on a Lib to control GoPro cameras and would like to try to wake them up via WoL. However, I wonder which WiFi should I connect to in STA mode when the cameras are asleep?
Can you help me?

**Comment by a7md0** [comment]
Hello, I don't believe this is possible without connecting both the cameras and the WakeOnLan device to the same network.
