### ISSUE TITLE
Could it be possible to receive WoL packets ?

### ISSUE THREAD

**Issue by shodanx2** [a7md0/WakeOnLan#2]
I imagine some people would like to just receive WoL packets either from the ethernet port or the wifi.

I have a special need, I would like to receive WoL packets over wifi while in promiscuous mode.

My use case is my esp32 is connected to my PC's atx power button, and I want the esp32 to push that button (really just short the pins for an instance using a micro relay) when it receives a WoL packet destined the my PC's MAC address. (I'd prefer this esp32 not have it's own IP address if possible, just a passive listening for WoL packets that are not destined to it)

This is for a PC with a USB wifi adapter that cannot WoL over wifi.

**Comment by a7md0** [comment]
Out of this package scope

**Comment by RakibRyan** [comment]
> I imagine some people would like to just receive WoL packets either from the ethernet port or the wifi.
> 
> I have a special need, I would like to receive WoL packets over wifi while in promiscuous mode.
> 
> My use case is my esp32 is connected to my PC's atx power button, and I want the esp32 to push that button (really just short the pins for an instance using a micro relay) when it receives a WoL packet destined the my PC's MAC address. (I'd prefer this esp32 not have it's own IP address if possible, just a passive listening for WoL packets that are not destined to it)
> 
> This is for a PC with a USB wifi adapter that cannot WoL over wifi.

I imagine you are trying to make a remote pc on off switch maybe bios & a few more possibilities but you realize your wol doesn't work over WiFi. So, decided to make one yourself. We'll I'm trying to do the same. Let me know if you made a full solution. As for me I only wrote code up to control all the relays with various durations. Help would be much appreciated.

**Comment by shodanx2** [comment]
That is correct
I have an old PC with only wifi and no wake on lan functionality.

My plan was to hook up a esp32 to standby power and an opto coupler in
parallel with the power switch.

Also led pwr to gpio input to determine current state.

Listen for a wake on packet and if computer is off or sleeping, then press
power button.

This could add WoL function to any computer.

And from there it's a short way to making a rudimentary IPMI interface for
any motherboard. Perhaps better sense boot status and do thing like "press
f1" on a stuck bios automatically.

However, for now I have other projects.

The key here is, listening to this packet. Esp32 on standby power doesn't
need to sleep.

Just code to trigger a function when WoL packet is received.

I heard chat got can program this.

Once we have this functionality, the rest is easy, just read and flip some
gpio. Web server for interface and soft vusb to send keystrokes if need be.

On Tuesday, January 3, 2023, Rakib Ryan ***@***.***> wrote:
> I imagine some people would like to just receive WoL packets either from
the ethernet port or the wifi.
>
> I have a special need, I would like to receive WoL packets over wifi
while in promiscuous mode.
>
> My use case is my esp32 is connected to my PC's atx power button, and I
want the esp32 to push that button (really just short the pins for an
instance using a micro relay) when it receives a WoL packet destined the my
PC's MAC address. (I'd prefer this esp32 not have it's own IP address if
possible, just a passive listening for WoL packets that are not destined to
it)
>
> This is for a PC with a USB wifi adapter that cannot WoL over wifi.
>
> I imagine you are trying to make a remote pc on off switch maybe bios & a
few more possibilities but you realize your wol doesn't work over WiFi. So,
decided to make one yourself. We'll I'm trying to do the same. Let me know
if you made a full solution. As for me I only wrote code up to control all
the relays with various durations. Help would be much appreciated.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci4.googleusercontent.com/proxy/XuOnhLRms_VlE2o9OWeDBkaW9ow739umKThDmc41xgOgIVUoTy_OwGAnfxubXHeORkcLFn8WVf29MYyNQc7sRplQjnfB7pi-VZ7Qi3_ku_aJlWKeak_tmEPT78qVT7LCMayRWNkpghbQloyBh4407ZFSh0R9BrvNsj5LTbR0GFjGxCBcy3_ZMeOIgFswwAnf_uERGaHpzHPoA8yAszAvDdhzzgvtE8QKUhfQatvpCw=s0-d-e1-ft#https://github.com/notifications/beacon/ACRBHPMML7CB3ZDLYJEWTR3WQSO47A5CNFSM5G3F5HLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOKGWKZSI.gif>Message
ID: ***@***.***>
